language: go

# S: Build Lifecycle
install:
  # Get ink command
  - go get github.com/InkProject/ink
  # Run ink build to generate static blog files
  - ink build
# before_script

script:
  # Switch to the ouput directory, the static blog files
  - cd ./docs
  # git init, config, add, commit and push the static blog files
  # to the github pages branch
  - git init
  - git config user.name "osromusic"
  - git config user.email "osromusic@gmail.com"
  - git add .
  - git commit -m "update docs"
  - git push --force --quiet "https://${GH_TOKEN2}@${GH_REF}" master:master
  
  # after script
  # E: Build Lifecycle
  
branches:
  only:
    - blog-source
env:
  global:
    - GH_REF: github.com/osromusic/Blog2
